name: Generate Apks

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]
     
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Chmod Gradle
        run: chmod +x ./gradlew

      - name: Build Gradle
        run: ./gradlew build

      - name: Assemble Debug Apk
        run: ./gradlew assembleDebug

      - name: Assemble Release Apk
        run: ./gradlew assembleRelease

      - name: Upload Debug Apk
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: ./EcuTweaker/build/outputs/apk/debug/*.apk

      - name: Upload Release Apk
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: ./EcuTweaker/build/outputs/apk/release/*.apk

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4

      - name: Download Debug Apk
        uses: actions/download-artifact@v4
        with:
          name: debug-apk
          path: apks/debug

      - name: Download Release Apk
        uses: actions/download-artifact@v4
        with:
          name: release-apk
          path: apks/release

      - name: Get tag name
        id: tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.tag.outputs.TAG_NAME }}
          tag_name: ${{ steps.tag.outputs.TAG_NAME }}
          files: |
            apks/debug/*.apk
            apks/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
